Update README.md
ioveracker/mac-init pull request #6
Opened 2018-10-11 06:58 UTC by CrickSoldier

I have done some changes in Prerequisites section to make it better for the viewer.

2018-10-11 18:21 UTC, voidrender requested changes
Thanks! I like this idea, but would like to request a slight change to the wording.

2018-10-11 18:21 UTC, ioveracker commented on README.md
> +The it needed is [Homebrew](http://brew.sh/),you can install the homebrew by coping and pasting the following command in terminal.
How about this instead?

```
[Homebrew](http://brew.sh/) is required to run these scripts. You can install Homebrew by copying and pasting the following command into your terminal.
```

2018-10-12 07:22 UTC, CrickSoldier commented
I had changed the file as per the suggestion.

2018-10-12 15:54 UTC, voidrender approved these changes
Thanks!

2018-10-12 15:54 UTC, merged